name: container
on: push

jobs:
  helm-docker:
    runs-on: ubuntu-latest
    container:
      image: dockerkam47722/helm-eks-action:1.0.0
    steps:
      - uses: actions/checkout@v2
    
      - name: Check Helm Version
        run: |
          helm version
      
      - name: Download Helm Repo
        run: |
          helm repo add akhq https://akhq.io/
          
      - name: Deploy Helm Chart
        run: |
          helm upgrade --install akhq akhq/akhq --namespace tools --kubeconfig ${{ secrets.KUBE_CONFIG_DATA }}   
          

    
