name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: alpine/helm:3.7.2
    steps:
      - uses: actions/checkout@v2
    
      - name: Check Helm Version
        run: |
          helm version
      
      - name: Download Helm Repo
        run: |
          helm repo add akhq https://akhq.io/

    
